### PR TITLE
[ascension.rb] creation of Ascension module and infomon parsing

### PR DESCRIPTION
**Pull request by mrhoribu**
Creates an Ascension module as part of PSMS due to relying on similar architecture and system backend.

### CODE REVIEW

**Review by OSXLich-Doug — COMMENTED** [review]
in `parser.rb`

```          if category =~ /Ascesion/
            @psm_cat = 'ascension'
          else
            @psm_cat = 'psm'
          end
```

Suspect that should be `if category =~ /Ascension/

Three places.

**Comment by mrhoribu** [comment]
> in `parser.rb`
> 
> ```
>           if category =~ /Ascesion/
>             @psm_cat = 'ascension'
>           else
>             @psm_cat = 'psm'
>           end
> ```
> 
> Suspect that should be `if category =~ /Ascension/`
> 
> Three places.

Good catch. Thanks.

**Comment by mrhoribu** [comment]
Updated PR with additional debug output for Mutex lock/unlock/synchronize incase of error. Also updated SkillEnd pattern match to ignore if not currently in a mutex lock state as TPs being earned messaging was triggering match.
```
You've gained 1 physical and mental training point.
Unconverting 1 Mnt points to return 2 Phy points. (See HELP TPS)
--- Lich: error: Pattern::SkillEnd: Attempt to unlock a mutex which is not locked
Training Points: 67 Phy 0 Mnt (4326 Phy converted to Mnt)
```

**Review by OSXLich-Doug — APPROVED** [review]
LGTM

**Pull request merged**
