### PR TITLE
[scripts] [autostart] DR messaging and one small logic change

### PR DESCRIPTION
**Pull request by MahtraDR**
Screenshot from 2022-03-31 20-35-52

### CODE REVIEW

**Comment by MahtraDR** [comment]
This should go after https://github.com/elanthia-online/lich-5/pull/179

**Comment by OSXLich-Doug** [comment]
Does this display properly on Genie and ProfantiyFE for DR folks?  I ask because on Wizard and Avalon FE, it will render to the screen as follows:

```>;e _respond(" <pushBold/># DR-Scripts do not normally usually use this script. #<popBold/>\n")
--- Lich: exec2 active.
 <pushBold/># DR-Scripts do not normally usually use this script. #<popBold/>
--- Lich: exec2 has exited.```

**Comment by MahtraDR** [comment]
> Does this display properly on Genie and ProfantiyFE for DR folks? I ask because on Wizard and Avalon FE, it will render to the screen as follows:
> 
> ```
> >;e _respond(" <pushBold/># DR-Scripts do not normally usually use this script. #<popBold/>\n")
> --- Lich: exec2 active.
>  <pushBold/># DR-Scripts do not normally usually use this script. #<popBold/>
> --- Lich: exec2 has exited.
> ```

My screenshot is on profanity, so that certainly works. I would expect genie not to work as is, but I was ok with that. Wrayth not working is more problematic. :) I'll test wrayth when I wake up, and modify as needed.

**Comment by mrhoribu** [comment]
`Lich::Messaging.monsterbold` should be usable here.
```ruby
    #from messaging.rb
    def self.monsterbold(msg)
      return monsterbold_start + self.xml_encode(msg) + monsterbold_end
    end
```
So long as the `monsterbold_start` and `monsterbold_end` accounts for Genie, it should be good.
```ruby
#from lich.rbw
def monsterbold_start
  if $frontend =~ /^(?:wizard|avalon)$/
    "\034GSL\r\n"
  elsif $frontend =~ /^(?:stormfront|frostbite)$/
    '<pushBold/>'
  elsif $frontend == 'profanity'
    '<b>'
  else
    ''
  end
end

def monsterbold_end
  if $frontend =~ /^(?:wizard|avalon)$/
    "\034GSM\r\n"
  elsif $frontend =~ /^(?:stormfront|frostbite)$/
    '<popBold/>'
  elsif $frontend == 'profanity'
    '</b>'
  else
    ''
  end
end
```

**Comment by MahtraDR** [comment]
Suits me for now. There is genie-specific code we can use, but we're working on maybe not needing that.

**Pull request merged**
