### PR TITLE
[lich.rbw] Clean lich char comma or semi-colon

### PR DESCRIPTION
**Pull request by MahtraDR**
Allows usage of a comma, or the semi-colon as the lich char. In the past, Genie couldn't handle semi-colons, but that's no longer the case.

I don't believe adding the comma as a second command character breaks anything...

### CODE REVIEW

**Comment by OSXLich-Doug** [comment]
I'm not sure about the goal of this PR, but it does have some impact.  I haven't tested it completely yet for logical impact, but at least optically this can lead to things like what is returned in `;help` .  Most GS scripts use (copy) the same feature to display help for the script itself.

Does DR have any `;<script> help` displays for scripts?  Does it look the same?

**Comment by asechrest** [comment]
I am currently on mobile and haven't really looked at this PR. But DR does have script help output. The functionality is built into our script argument parser. I am currently working on a long-term project I'm creating more robust help output to include output and description of the yaml settings used in the script.

**Comment by asechrest** [comment]
Commenting on your edit. Good point about go2. I know there is help functionality built into that script. Separately, we have a script argument parser that lives in dependency, and responds to a help argument, then outputs The required and optional arguments and a description of what they are for.

**Comment by MahtraDR** [comment]
This depends on https://github.com/elanthia-online/lich-5/pull/183

**Pull request merged**
