### PR TITLE
feat: ExecName - Named execs

### PR DESCRIPTION
**Pull request by mrhoribu**
Allow for naming your exec by launching via following:
```
>;execname log echo '1'   
--- Lich: log1 active.    
[log1: 1]                 
--- Lich: log1 has exited.
```

### CODE REVIEW

**Comment by MahtraDR** [comment]
Please give me a short version of this? Like `exec` can be called `e` and `execquiet` 'eq`

Maybe `en` ?

**Comment by mrhoribu** [comment]
> Please give me a short version of this? Like `exec` can be called `e` and `execquiet` 'eq`
> 
> Maybe `en` ?

I was thinking this but apparently there was already a shortened version for `;en` that does old school trusted:
```ruby
    elsif cmd =~ /^(?:exec|e)(q)?(n)? (.+)$/
      cmd_data = $3
      ExecScript.start(cmd_data, { :quiet => $1, :trusted => ($2.nil? and RUBY_VERSION =~ /^2\.[012]\./) })
```
I thought about stealing/taking that out of the base version to be reused, since trust isn't really a thing anymore lin Lich 5.7.0 and newer versions of Ruby. Thoughts?
I could change that to:
```ruby
    elsif cmd =~ /^(?:exec|e)(q)? (.+)$/
      cmd_data = $3
      ExecScript.start(cmd_data, { :quiet => $1 })
    elsif cmd =~ /^(?:execname|en) ([\w\d-]+) (.+)$/
      execname = $1
      cmd_data = $2
      ExecScript.start(cmd_data, { :name => execname })
```

**Comment by MahtraDR** [comment]
I like it. Trust is dead.

**Comment by mrhoribu** [comment]
Only issue I could see is people that currently try to launch scripts that begin with the letters `en` and don't type more than that, will find themselves running into an issue if that script is normally launched with 2 command line options. But looking over the scripts on GS4 side, I don't think any of these scripts currently would be started in that way so likely no conflict:
```
      enchantcheck.lic
      enchantnotes.lic
    encumbrancebar.lic
           enhance.lic
         enhancive.lic
enhancive_detector.lic
   enhancive_watch.lic
          enhsaver.lic
            enlake.lic
    ensorcell_calc.lic
 ensorcell_tracker.lic
```

**Pull request merged**
