### PR TITLE
[lich.rbw] Moving map-related require-relatives to accomodate Genie, and other direct-connect clients

### PR DESCRIPTION
**Pull request by MahtraDR**
Tested, no regressions. Gets rid of the problem where we don't detect the game without `--login` or via the launcher.

Note, with this change, lich5 works perfectly well with DR and Genie, using the existing process documented here https://github.com/GenieClient/Genie4/wiki/02.-Connecting-and-Profiles

### CODE REVIEW

**Comment by MahtraDR** [comment]
> Would also need to add the includes in both the `--fallen` and the `--shattered` sections as well for each game in order for this to work fully.

We also need to figure out how to get it in with the launcher. I'll spend more time thinking about this today.

**Comment by MahtraDR** [comment]
@OSXLich-Doug @mrhoribu How's this instead?

**Comment by MahtraDR** [comment]
@OSXLich-Doug 's fix on Discord looks like a better solution than this.

**Comment by OSXLich-Doug** [comment]
Closing without merge per agreement.

**Pull request closed without merging**
