### PR TITLE
[parser.rb] bugfix for SKILL BASE output start msg

### PR DESCRIPTION
**Pull request by mrhoribu**
Update SkillStart to match for SKILL and SKILL BASE

### CODE REVIEW

**Comment by OSXLich-Doug** [comment]
I'm not sure of the value to this change PR

**Comment by mrhoribu** [comment]
> I'm not sure of the value to this change PR

Without this change, doing a SKILL BASE doesn't trigger the batch start processing for the skill group as it doesn't match the regex as the current regex only matches SKILLS or SKILLS FULL. Not SKILLS BASE or SKILLS FULL BASE. So you end up getting a massive error due to the mutex not getting locked and the initialization of the skills array to push values into.

**Comment by mrhoribu** [comment]
SKILLS BASE is what is shown after updating your skills from a GOALS change.

**Comment by OSXLich-Doug** [comment]
I see.  For goals (SKILL BASE) you get a clean run.  For full skill base, you get a ton of untrained skills.  Is there a way to isolate it in regex (rather than logic) so we don't get a ton of zero values in the DB?

**Comment by OSXLich-Doug** [comment]
Sorry, wrong button.  Reopened

**Comment by mrhoribu** [comment]
> I see. For goals (SKILL BASE) you get a clean run. For full skill base, you get a ton of untrained skills. Is there a way to isolate it in regex (rather than logic) so we don't get a ton of zero values in the DB?

There isn't any other logic to clean up. The only issue was triggering the START capture to lock the mutex. The rest still works fine. The output from `SKILL` vs `SKILL BASE` matches the other regex used to fill out various skills and end the capture. The only time you'd get 0 values is if you do a FULL for either, and this PR wasn't opened to address that.

**Comment by OSXLich-Doug** [comment]
Agree that it wasn't opened to address it, but it did cause zero entry populations.  A lingering problem we have from the PSMs landing with 0 / 0 in the db as well.  But that's ok.  I'll address it in another PR.

**Review by OSXLich-Doug — APPROVED** [review]
LGTM for what it was intended to do.

**Pull request merged**
