### PR TITLE
Script CLASS empty array initializing bugfix

### PR DESCRIPTION
**Pull request by OSXLich-Doug**
Preventing class Script from pushing empty arguments to scripts being loaded

This change modifies class Script to prevent empty or nil arguments being passed to scripts as they're being loaded.  Scripts that do not accept arguments were unaffected by recent Lich 5.4.x changes, but those scripts that did accept arguments, but did not intend to catch NIL or EMPTY arguments showed erratic behavior.

edited for spelling

### CODE REVIEW

**Comment by mrhoribu** [comment]
Issue is due to fix for populating script.vars[0] with entire set of vars if Array[] is pushed to Script initialization. Unfortunately, if empty array was pushed, it would go from being empty`[]` to being `[""]`.

**Comment by mrhoribu** [comment]
> Issue is due to fix for populating script.vars[0] with entire set of vars if Array[] is pushed to Script initialization. Unfortunately, if empty array was pushed, it would go from being empty`[]` to being `[""]`.

This was introduced with DragonRealms fixes from #133

**Comment by mrhoribu** [comment]
For more info dragon-realms/dr-lich/issues/46

**Comment by MahtraDR** [comment]
With this change. 
```
--- Lich: dependency active.                                                                                                                                                                                                                  
[dependency: ***INVALID ARGUMENTS DON'T MATCH ANY PATTERN***]                                                                                                                                                                                 
Provided Arguments: ''                                                                                                                                                                                                                        
                                                                                                                                                                                                                                              
  ;dependency [debug] [install]                                                                                                                                                                                                               
   debug                                                                                                                                                                                                                                      
   install                                                                                                                                                                                                                                    
--- Lich: dependency has exited.            
```
Without this change, dependency loads silently as expect.


```
>;autostart list                                                                                                                                                                                                                              
--- Global autostart scripts: alias, lnet, repository (args: download-updates), dependency
```

**Review by MahtraDR — APPROVED** [review]
Fine for the DR side.

**Pull request merged**
